plugins { id 'com.android.application' }

android {
    namespace 'it.paolo.scortetecniche'
    compileSdk 35

    defaultConfig {
        applicationId 'it.paolo.scortetecniche'
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName '1.1'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
